params.ref = "/Users/dhusiakalyani/nextflowGenomeIndex/ref/Agy99.fasta"
params.output_dir = "/Users/dhusiakalyani/nextflowGenomeIndex/ref/index_files"

process index {

    input:
    path genome

    output:
    path "$params.output_dir/*"  // Capture all the index files generated by bwa index

    script:
    """
    # Get the directory of the input genome file
    genome_dir=\$(dirname $genome)

    # Run bwa index and specify the output directory to be the same as the input file's directory
    bwa index -p $params.output_dir/\$(basename \$genome .fasta) $genome
    """
    
    // Set workDir inside the script block explicitly to the genome file's directory
    workDir { dirname(genome) }
    
    // Use publishDir to copy the output files to the target folder after the process finishes
    publishDir "$params.output_dir", mode: 'copy'
}

workflow {
    ref_ch = Channel.fromPath(params.ref)

    index(ref_ch)
}